### ISSUE TITLE
Cannot run the programs

### ISSUE THREAD

**Issue by stefank17** [anetczuk/LinakDeskApp#5]
I followed the README.md and could not run the programs. Im using ubuntu 20. Where can I get these dependencies prompted in the error message?

# Steps to reproduce

1. clone repository
2. python -m venv env
3. activate newly created python environment
4. pip install dependencies given in README.md
5. run these commands given in Actual result section

# Expected result

Error should not be throwed.

# Actual result

- When doing: ./src/linakdeskctl

```bash
./src/linakdeskctl
Traceback (most recent call last):
  File "/home/linux_user/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/linux_user/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/linux_user/Desktop/some_folder/some_folder/LinakDeskApp/src/linakdeskapp/__main__.py", line 7, in <module>
    from .main import main
  File "/home/linux_user/Desktop/some_folder/some_folder/LinakDeskApp/src/linakdeskapp/main.py", line 46, in <module>
    from linakdeskapp.bt_device_connector import BTDeviceConnector
  File "/home/linux_user/Desktop/some_folder/some_folder/LinakDeskApp/src/linakdeskapp/bt_device_connector.py", line 43, in <module>
    from linak_dpg_bt.linak_device import LinakDesk
ModuleNotFoundError: No module named 'linak_dpg_bt'
```

- When doing: ./src/linakdeskapp/main.py

```bash
./src/linakdeskapp/main.py
Traceback (most recent call last):
  File "./src/linakdeskapp/main.py", line 46, in <module>
    from linakdeskapp.bt_device_connector import BTDeviceConnector
  File "/home/linux_user/Desktop/some_folder/some_folder/LinakDeskApp/src/linakdeskapp/bt_device_connector.py", line 43, in <module>
    from linak_dpg_bt.linak_device import LinakDesk
ModuleNotFoundError: No module named 'linak_dpg_bt'
```

- When doing: cd src; python3 -m linakdeskapp

```bash
cd src; python3 -m linakdeskapp
Traceback (most recent call last):
  File "/home/linux_user/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/linux_user/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/linux_user/Desktop/some_folder/some_folder/LinakDeskApp/src/linakdeskapp/__main__.py", line 7, in <module>
    from .main import main
  File "/home/linux_user/Desktop/some_folder/some_folder/LinakDeskApp/src/linakdeskapp/main.py", line 46, in <module>
    from linakdeskapp.bt_device_connector import BTDeviceConnector
  File "/home/linux_user/Desktop/some_folder/some_folder/LinakDeskApp/src/linakdeskapp/bt_device_connector.py", line 43, in <module>
    from linak_dpg_bt.linak_device import LinakDesk
ModuleNotFoundError: No module named 'linak_dpg_bt'
```

**Comment by anetczuk** [comment]
Hello Stefan,

the *linak_dpg_bt* module is a submodule placed in *{project_root}/lib/linak_dpg_bt*. To fetch it You can simply execute *configure_submodules.sh* script placed in project root dir.

**Comment by stefank17** [comment]
Thank you for the help.
