### ISSUE TITLE
error on startup: „ModuleNotFoundError: No module named 'linak_dpg_bt'”

### ISSUE THREAD

**Issue by Krandelbord** [anetczuk/LinakDeskApp#7]
When I try to start I get the following error:

LinakDeskApp/src$ python3 -m linakdeskapp*
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/emil/programy/LinakDeskApp/src/linakdeskapp/__main__.py", line 7, in <module>
    from .main import main
  File "/home/emil/programy/LinakDeskApp/src/linakdeskapp/main.py", line 46, in <module>
    from linakdeskapp.bt_device_connector import BTDeviceConnector
  File "/home/emil/programy/LinakDeskApp/src/linakdeskapp/bt_device_connector.py", line 43, in <module>
    from linak_dpg_bt.linak_device import LinakDesk
ModuleNotFoundError: No module named 'linak_dpg_bt'

**Comment by anetczuk** [comment]
You need to fetch git submodule before first use.
See #5 or _README_ for details.

**Comment by Krandelbord** [comment]
ah ok, thanks. Would be nice if installation process will be somewhat simpler.
Anyway I reached another exception, but that is another topic/issue.
