### ISSUE TITLE
exception during startup: The _init_toolbar function was deprecated in Matplotlib 3.3

### ISSUE THREAD

**Issue by Krandelbord** [anetczuk/LinakDeskApp#8]
When I try to start application I get the following error.

```
src$ python3 -m linakdeskapp*



2021-02-06 09:52:39,544 DEBUG    MainThread linakdeskapp.main:main [main.py:108] Starting the application
2021-02-06 09:52:39,544 DEBUG    MainThread linakdeskapp.main:main [main.py:109] Logger log file: /home/emil/programy/LinakDeskApp/src/log.txt
/home/emil/programy/LinakDeskApp/src/linakdeskapp/gui/mpl/mpl_toolbar.py:39: MatplotlibDeprecationWarning: 
The _init_toolbar function was deprecated in Matplotlib 3.3 and will be removed two minor releases later. Use __init__ instead.
  self._init_toolbar()    ## add current buttons
2021-02-06 09:52:39,655 ERROR    MainThread linakdeskapp.main:main [main.py:131] Exception occurred
Traceback (most recent call last):
  File "/home/emil/programy/LinakDeskApp/src/linakdeskapp/main.py", line 124, in main
    exitCode = runApp(args)
  File "/home/emil/programy/LinakDeskApp/src/linakdeskapp/main.py", line 77, in runApp
    window = MainWindow()
  File "/home/emil/programy/LinakDeskApp/src/linakdeskapp/gui/main_window.py", line 51, in __init__
    self.ui.setupUi(self)
  File "<string>", line 26, in setupUi
  File "/home/emil/programy/LinakDeskApp/src/linakdeskapp/gui/app_settings_widget.py", line 85, in __init__
    self.ui.setupUi(self)
  File "<string>", line 41, in setupUi
  File "/home/emil/programy/LinakDeskApp/src/linakdeskapp/gui/position_chart_widget.py", line 57, in __init__
    self.toolbar = DynamicToolbar(self.ui.positionChart, self)
  File "/home/emil/programy/LinakDeskApp/src/linakdeskapp/gui/mpl/mpl_toolbar.py", line 27, in __init__
    self.removeButton( 'Subplots' )
  File "/home/emil/programy/LinakDeskApp/src/linakdeskapp/gui/mpl/mpl_toolbar.py", line 39, in removeButton
    self._init_toolbar()    ## add current buttons
  File "/usr/lib/python3/dist-packages/matplotlib/cbook/deprecation.py", line 234, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/backend_bases.py", line 2942, in _init_toolbar
    raise NotImplementedError
NotImplementedError

2021-02-06 09:52:39,658 INFO     MainThread linakdeskapp.main:main [main.py:147] Calculation time:  113.75737190ms
```

**Comment by szszoke** [comment]
I am having the same issue on Manjaro. `matplotlib` comes from the `python-matplotlib-3.3.3-2` package.

**Comment by istepaniuk** [comment]
hapening also on Debian bullseye

**Comment by anetczuk** [comment]
Fixed, please test/verify with new code

**Comment by anetczuk** [comment]
Btw, same as #3
